// AUTO-GENERATED by build.js — do not edit manually.
const TEMPLATES = {
  "BFS: Graph": `const START_NODE_INDEX = 0;

function traverseGraph(adjacencyList) {
  let queue = [START_NODE_INDEX];
  const seen = new Set([START_NODE_INDEX]);
  let result = 0;

  while (queue.length) {
    const nextQueue = [];

    for (const nodeIndex of queue) {
      // DO SOME LOGIC AT THIS POINT
      // e.g., result += nodeValue;

      const neighbors = adjacencyList[nodeIndex];

      for (const neighbor of neighbors) {
        if (!seen.has(neighbor)) {
          seen.add(neighbor);
          nextQueue.push(neighbor);
        }
      }
    }

    queue = nextQueue;
  }

  return result;
}`,

  "BFS: Matrix": `const DIRECTIONS = [
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
];

function traverseMatrix(matrix, startNode) {
  const rows = matrix.length;
  const cols = matrix[0].length;

  let queue = [startNode];
  const seen = new Set([stringifyNode(startNode)]);
  while (queue.length) {
    const nextLevel = [];

    for (const node of queue) {
      // DO SOME LOGIC FOR CURRENT NODE AT THIS POINT

      const { row, col } = node;

      for (const [dr, dc] of DIRECTIONS) {
        const nr = row + dr;
        const nc = col + dc;
        const nextNode = { row: nr, col: nc };
        const key = stringifyNode(nextNode);

        if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && !seen.has(key)) {
          // DO LOGIC AT THIS POINT
          seen.add(key);
          nextLevel.push(nextNode);
        }
      }
    }

    queue = nextLevel;
  }
}

function getNeighbors(node) {
  const { row, col } = node;
  const result = [];
  for (const direction of DIRECTIONS) {
    const [deltaRow, deltaCol] = direction;
    result.push({ row: row + deltaRow, col: col + deltaCol });
  }
  return result;
}

function stringifyNode(node) {
  const { row, col } = node;
  return [row, col].join(",");
}`,

  "BFS: Tree": `function traverseTree(root) {
  let queue = [root];
  let result = 0;

  while (queue.length) {
    // DO LOGIC FOR CURRENT LEVEL

    const nextQueue = [];

    for (const node of queue) {
      // DO LOGIC FOR CURRENT NODE
      // e.g.
      // if (node === target){
      //   return node;
      // }
      if (node.left) {
        nextQueue.push(node.left);
      }
      if (node.right) {
        nextQueue.push(node.right);
      }
    }

    queue = nextQueue;
  }

  return result;
  // alternatively: return \`-1\` for not found
  // i.e. if there was no \`return\` call above in the \`for\` loop
}`,

  "DFS: Binary Tree (Iterative)": `function traverseGraph(root) {
  const stack = [root];
  let result = 0;
  while (stack.length) {
    let node = stack.pop();

    // DO SOME LOGIC AT THIS POINT

    if (node.left) {
      stack.push(node.left);
    }
    if (node.right) {
      stack.push(node.right);
    }
  }
  return result;
}`,

  "DFS: Binary Tree (Recursive, Find Target)": `function traverseGraph(node, target) {
  if (node === null) {
    return null;
  }
  if (node === target) {
    return node;
  }
  return traverseGraph(node.left, target) || traverseGraph(node.right, target);
}`,

  "DFS: Graph": `function traverseGraph(startNode) {
  const seen = new Set();

  function dfs(curr) {
    for (const neighbor of curr.neighbors) {
      if (seen.has(neighbor)) {
        continue;
      }
      seen.add(neighbor);
      dfs(neighbor);
    }
  }

  seen.add(startNode);
  dfs(startNode);
}`,

  "DFS: Graph (Iterative Aggregation)": `function traverseGraph(startNode) {
  const seen = new Set([startNode]);
  const stack = [startNode];
  let result = 0;

  while (stack.length) {
    const node = stack.pop();
    // DO SOME LOGIC AT THIS POINT
    for (const neighbor of node.neighbors){
      if (!seen.has(neighbor)) {
        seen.add(neighbor);
        stack.push(neighbor);
      }
    }
  }

        return result;
}`,

  "DFS: Graph (Recursive Aggregation)": `function traverseGraph(startNode) {
  const seen = new Set();

  function dfs(node) {
    let result = 0;
    // DO SOME LOGIC AT THIS POINT
    for (const neighbor of node.neighbors) {
      if (!seen.has(neighbor)) {
        seen.add(neighbor);
        result += dfs(neighbor);
      }
    }
    return result;
  }

  seen.add(startNode);
  return dfs(startNode);
}`,

  "Backtracking: Aggregation": `const INITIAL_VALUE = 0;

function traverseGraph(startIndex, ...additionalStates) {
  if (isLeaf(startIndex)) {
    return 1;
  }
  let result = INITIAL_VALUE;
  for (const edge of getEdges(startIndex, ...additionalStates)) {
    if (additionalStates) {
      // update additionalStates
    }
    const toAdd = traverseGraph(startIndex + edge.length, ...additionalStates);
    result = aggregate(result, toAdd);
    if (additionalStates) {
      // revert additionalStates if necessary
    }
  }
  return result;
}`,

  "Backtracking: Basic": `function traverseGraph(startIndex, path = [], res = [], ...additionalStates) {
  // for \`additionalStates\` include any additional states
  if (isLeaf(startIndex)) {
    res.push([...path]);
  }
  for (const edge of getEdges(startIndex, ...additionalStates)) {
    if (!isValid(edge)) {
      continue;
    }
    path.push(edge);
    if (additionalStates) {
      // update additionalStates
    }
    traverseGraph(startIndex + edge.length, path, res, ...additionalStates);
    if (additionalStates) {
      // revert additionalStates (if necessary)
    }
    path.pop();
  }
}`,

  "Binary Search: Insertion Point (First)": `function findFirstInsertionPoint(nums, target) {
  let left = 0;
  let right = nums.length - 1;
  let firstMatch = nums.length;

  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] >= target) {
      firstMatch = mid;
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return firstMatch;
}`,

  "Binary Search: Insertion Point (Last)": `function findLastInsertionPoint(nums, target) {
  let left = 0;
  let right = nums.length - 1;
  let lastMatch = nums.length;

  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] > target) {
      lastMatch = mid;
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return lastMatch;
}`,

  "Binary Search: Insertion Point (Unique)": `function findMatchOrInsertionPt(nums, target) {
  let left = 0;
  let right = nums.length - 1;

  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] === target) {
      // DO SOME LOGIC AT THIS POINT
      return mid;
    } else if (nums[mid] > target) {
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return left;
}`,

  "Binary Search: Find Match (First)": `function findMatchOrInsertionPt(nums, target) {
  let left = 0;
  let right = nums.length - 1;
  let firstMatch = -1;

  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] === target) {
      firstMatch = mid;
      right = mid - 1;
    } else if (nums[mid] > target) {
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return firstMatch;
}`,

  "Binary Search: Find Match (Last)": `function findLastMatch(nums, target) {
  let left = 0;
  let right = nums.length - 1;
  let lastMatch = -1;

  while (left <= right) {
    const mid = Math.floor((left + right) / 2);
    if (nums[mid] === target) {
      lastMatch = mid;
      left = mid + 1;
    } else if (nums[mid] > target) {
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return lastMatch;
}`,

  "Binary Search: Find Match (Unique)": `function findMatchOrInsertionPt(nums, target) {
  let left = 0;
  let right = nums.length - 1;

  while (left <= right) {
    const mid = left + Math.floor((right - left) / 2);
    if (nums[mid] === target) {
      return mid;
    } else if (nums[mid] > target) {
      right = mid - 1;
    } else {
      left = mid + 1;
    }
  }

  return -1;
}`,

  "Dynamic Programming: Bottom-Up": `function bottomUpDP(n) {
  if (n <= 1) {
    return n;
  }

  let prev = 0;
  let curr = 1;

  for (let i = 2; i <= n; i++) {
    const next = curr + prev;
    prev = curr;
    curr = next;
  }

  return curr;
}`,

  "Dynamic Programming: Top-Down": `function topDownDP(nums) {
  let memo = new Array(nums.length).fill(-1);

  function dp(i) {
    // handle base cases, e.g.
    if (i <= 1) {
      return i;
    }

    // get from memo
    if (memo[i] !== -1) {
      return memo[i];
    }

    // recurrence relation, e.g.
    let result = dp(i - 1) + dp(i - 2);

    memo[i] = result;
    return result;
  }

  return dp(nums.length - 1);
}`,

  "Linked List": `function reverseLinkedList(head) {
  let prev = null;
  let curr = head;
  while (curr) {
    const next = curr.next;
    curr.next = prev;
    prev = curr;
    curr = next;
  }
  return prev;
}`,

  "Stack": `class MonoIncreasingStack {
  #stack = [];
  #someImportantValue = 0;

  constructor(entriesToInsert) {
    this.insertEntries(entriesToInsert);
  }

  insertEntries(nums) {
    for (const num of nums) {
      while (this.#stack.length > 0 && this.#stack.at(-1) > num) {
        // OPTIONAL: DO SOME LOGIC AT THIS POINT

        const popped = this.#stack.pop();

        // OPTIONAL: DO SOME LOGIC AT THIS POINT e.g.
        this.#someImportantValue += popped;
      }

      this.#stack.push(num);
    }
  }

  get value() {
    return this.#someImportantValue;
  }
}`,

  "Trie": `class TrieNode {
  #children = new Map();
  #isEndOfWord = false;

  get children() {
    return this.#children;
  }

  get isEndOfWord() {
    return this.#isEndOfWord;
  }

  set isEndOfWord(isEnd) {
    this.#isEndOfWord = isEnd;
  }
}

class Trie {
  #root = new TrieNode();

  insert(word) {
    let current = this.#root;
    for (const char of word) {
      if (!current.children.has(char)) {
        current.children.set(char, new TrieNode());
      }
      current = current.children.get(char);
    }
    current.isEndOfWord = true;
  }

  search(word) {
    const node = this.#traverse(word);
    if (node === null) {
      return false;
    }
    return node.isEndOfWord;
  }

  startsWith(prefix) {
    return this.#traverse(prefix) !== null;
  }

  #traverse(string) {
    let current = this.#root;
    for (const char of string) {
      if (!current.children.has(char)) {
        return null;
      }
      current = current.children.get(char);
    }
    return current;
  }
}`,

  "Union Find": `class UnionFind {
  #id = new Map();

  find(x) {
    const match = this.#id.get(x);
    if (match === undefined || match === x) {
      return x;
    }
    const root = this.find(match);
    this.#id.set(x, root);
    return root;
  }

  union(x, y) {
    const rootX = this.find(x);
    const rootY = this.find(y);
    if (rootX !== rootY) {
      this.#id.set(rootX, rootY);
    }
  }
}`,

  "Two Pointers: Fast & Slow": `function twoPointersFastSlow(nums) {
  let slow = 0;
  let fast = 0;
  let result = 0;

  while (fast < nums.length) {
    // DO SOME LOGIC AT THIS POINT

    if (check(nums[slow], nums[fast])) {
      slow++;
    }
    fast++;
  }

  return result;
}`,

  "Two Pointers: Fast & Slow (Linked List)": `function twoPointersFastSlowLinkedList(head) {
  let slow = head;
  let fast = head;
  let result = 0;

  while (fast?.next) {
    // DO SOME LOGIC AT THIS POINT

    slow = slow.next;
    fast = fast.next.next;
  }

  return result;
}`,

  "Two Pointers: Opposite Ends": `function twoPointersOpposite(nums) {
  let left = 0;
  let right = nums.length - 1;
  let result = 0;
  while (left < right) {
    // DO SOME LOGIC AT THIS POINT

    if (check(nums[left], nums[right])) {
      left++;
    } else {
      right--;
    }
  }
  return result;
}`,

  "Two Pointers: Two Inputs": `function twoPointersTwoInputs(nums1, nums2) {
  let p1 = 0;
  let p2 = 0;
  let result = 0;

  while (p1 < nums1.length && p2 < nums2.length) {
    // DO SOME LOGIC AT THIS POINT

    if (check(nums1[p1], nums2[p2])) {
      p1++;
    } else {
      p2++;
    }
  }

  while (p1 < nums1.length) {
    // DO SOME LOGIC AT THIS POINT

    p1++;
  }

  while (p2 < nums2.length) {
    // DO SOME LOGIC AT THIS POINT

    p2++;
  }

  return result;
}`,

  "Prefix Sum": `function buildPrefixSum(arr) {
  let prefixSum = new Array(arr.length);
  prefixSum[0] = arr[0];
  for (let i = 1; i < arr.length; i++) {
    prefixSum[i] = prefixSum[i - 1] + arr[i];
  }
  return prefixSum;
}

// query prefix sum for range [left, right] (inclusive)
function queryRange(prefixSum, left, right) {
  if (left === 0) {
    return prefixSum[right];
  }
  return prefixSum[right] - prefixSum[left - 1];
}`,

  "Sliding Window: Fixed": `function findMaxLengthSlidingWindow(nums, windowSize) {
  let currentSum = 0;
  for (let i = 0; i < windowSize; i++) {
    currentSum += nums[i];
  }
  let maxSum = currentSum;
  let left = 0;
  for (let right = windowSize; right < nums.length; right++) {
    currentSum += nums[right];
    currentSum -= nums[left];
    left++;
    maxSum = Math.max(maxSum, currentSum);
  }
  return maxSum;
}`,

  "Sliding Window: Longest": `function findLongestSlidingWindow(nums, target) {
  let sum = 0;
  let maxLength = 0;
  let left = 0;
  for (let right = 0; right < nums.length; right++) {
    sum += nums[right];
    while (sum > target && left <= right) {
      sum -= nums[left];
      left++;
    }
    const currLength = right - left + 1;
    maxLength = Math.max(maxLength, currLength);
  }
  return maxLength;
}`,

  "Sliding Window: Shortest": `function findShortestSlidingWindow(nums, target) {
  let sum = 0;
  let minLength = Infinity;
  let left = 0;
  for (let right = 0; right < nums.length; right++) {
    sum += nums[right];
    while (sum >= target) {
      minLength = Math.min(minLength, right - left + 1);
      sum -= nums[left];
      left++;
    }
  }
  return minLength === Infinity ? 0 : minLength;
}`,

};