#!/usr/bin/env node
// Generates extension/templates.js from the templates/ directory.
// Run: node build.js

const fs = require("fs");
const path = require("path");

const TEMPLATES_DIR = path.join(__dirname, "templates");
const OUT_FILE = path.join(__dirname, "extension", "templates.js");

// Maps folder name → group label shown in the context menu.
const FOLDER_LABEL = {
  BFS: "BFS",
  DFS: "DFS",
  backtracking: "Backtracking",
  binary_search: "Binary Search",
  dynamic_programming: "Dynamic Programming",
  sliding_window: "Sliding Window",
  pointers: "Two Pointers",
  prefix_sum: "Prefix Sum",
  stack: "Stack",
  trie: "Trie",
  linked_list: "Linked List",
  union_find: "Union Find",
};

// When a folder has only one file and the name is redundant (e.g. "trie/trie.js"),
// use just the group label with no variant suffix.
const SINGLE_FILE_GROUPS = new Set([
  "prefix_sum",
  "stack",
  "trie",
  "union_find",
  "linked_list",
]);

// Per-filename label overrides for anything title-case gets wrong.
const FILE_LABEL = {
  button_up_dp: "Bottom-Up",
  top_down_dp: "Top-Down",
  two_pointers_fast_slow: "Fast & Slow",
  two_pointers_fast_slow_linked_list: "Fast & Slow (Linked List)",
  two_pointers_opposite: "Opposite Ends",
  two_pointers_two_inputs: "Two Inputs",
  dfs_on_binary_tree_iterative: "Binary Tree (Iterative)",
  dfs_on_binary_tree_recursive_find_target: "Binary Tree (Recursive, Find Target)",
  dfs_on_graph: "Graph",
  dfs_on_graph_iterative_aggregation: "Graph (Iterative Aggregation)",
  dfs_on_graph_recursive_aggregation: "Graph (Recursive Aggregation)",
  bfs_on_graph: "Graph",
  bfs_on_matrix: "Matrix",
  bfs_on_tree: "Tree",
  backtracking_basic: "Basic",
  backtracking_aggregation: "Aggregation",
  binary_search_find_match_unique: "Find Match (Unique)",
  binary_search_find_match_first: "Find Match (First)",
  binary_search_find_match_last: "Find Match (Last)",
  binary_search_find_insertion_point_unique: "Insertion Point (Unique)",
  binary_search_find_insertion_point_first: "Insertion Point (First)",
  binary_search_find_insertion_point_last: "Insertion Point (Last)",
  sliding_window_fixed: "Fixed",
  sliding_window_longest: "Longest",
  sliding_window_shortest: "Shortest",
};

function toTitleCase(str) {
  return str.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function groupLabel(folderName) {
  return FOLDER_LABEL[folderName] ?? toTitleCase(folderName);
}

function variantLabel(folderName, fileName) {
  if (FILE_LABEL[fileName]) return FILE_LABEL[fileName];
  const prefix = folderName.toLowerCase().replace(/ /g, "_") + "_";
  const stripped = fileName.startsWith(prefix)
    ? fileName.slice(prefix.length)
    : fileName;
  return toTitleCase(stripped);
}

// Walk templates/ and collect { group, variant, code } entries.
const entries = [];

for (const category of fs.readdirSync(TEMPLATES_DIR).sort()) {
  const categoryPath = path.join(TEMPLATES_DIR, category);
  if (!fs.statSync(categoryPath).isDirectory()) continue;

  for (const folder of fs.readdirSync(categoryPath).sort()) {
    const folderPath = path.join(categoryPath, folder);
    if (!fs.statSync(folderPath).isDirectory()) continue;

    const group = groupLabel(folder);

    for (const file of fs.readdirSync(folderPath).sort()) {
      if (!file.endsWith(".js")) continue;
      const baseName = path.basename(file, ".js");
      const variant = variantLabel(folder, baseName);
      const key = SINGLE_FILE_GROUPS.has(folder)
        ? group
        : `${group}: ${variant}`;
      const code = fs.readFileSync(path.join(folderPath, file), "utf8").trimEnd();
      entries.push({ key, code });
    }
  }
}

// Serialize to JS.
const lines = ["// AUTO-GENERATED by build.js — do not edit manually.", "const TEMPLATES = {"];

for (const { key, code } of entries) {
  // Escape backticks and template literal ${ inside the code string.
  const escaped = code.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  lines.push(`  ${JSON.stringify(key)}: \`${escaped}\`,`);
  lines.push("");
}

lines.push("};");

fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
console.log(`Wrote ${entries.length} templates to ${OUT_FILE}`);
